[package]
name = "petra"
version = "0.1.0"
authors = ["BenCantCode"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
noise = "0.6.0"
bevy_fly_camera = "0.6.0"
